version: '3.8'

services:
  curvela_backend:
    build: .
    container_name: curvela_backend
    ports:
      - "8080:80" 
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=curvela_db;Username=karen;Password=karencurvela

  db:
    image: postgres:latest
    container_name: curvela_db
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: curvela_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
